import { GENERATED_HEALTH_EXERCISE_CATALOG } from '@/lib/healthExerciseCatalog.generated'
import type { HealthCatalogExercise } from '@/types/health'

export const HEALTH_BODY_PART_LABELS: Record<string, string> = {
  back: 'หลัง',
  cardio: 'คาร์ดิโอ',
  chest: 'อก',
  'lower arms': 'ท่อนแขน',
  'lower legs': 'น่อง',
  neck: 'คอ',
  shoulders: 'ไหล่',
  'upper arms': 'แขน',
  'upper legs': 'ขาและสะโพก',
  waist: 'แกนกลาง',
}

export const HEALTH_EQUIPMENT_LABELS: Record<string, string> = {
  assisted: 'เครื่องช่วย',
  band: 'ยางยืด',
  barbell: 'บาร์เบล',
  'body weight': 'ไม่ใช้อุปกรณ์',
  'bosu ball': 'โบซูบอล',
  cable: 'เคเบิล',
  dumbbell: 'ดัมเบล',
  'ez barbell': 'อีซีบาร์',
  'elliptical machine': 'เครื่องเดินวงรี',
  hammer: 'ค้อน',
  kettlebell: 'เคตเทิลเบล',
  'leverage machine': 'เครื่องเวท',
  'medicine ball': 'เมดิซีนบอล',
  'olympic barbell': 'โอลิมปิกบาร์',
  'resistance band': 'ยางต้านแรง',
  roller: 'โฟมโรลเลอร์',
  rope: 'เชือก',
  'sled machine': 'เครื่องสเลด',
  'skierg machine': 'เครื่องสกีเออร์ก',
  'smith machine': 'สมิธแมชชีน',
  'stability ball': 'บอลออกกำลัง',
  'stationary bike': 'จักรยานอยู่กับที่',
  'stepmill machine': 'เครื่องเดินบันได',
  'tire': 'ยางรถ',
  'trap bar': 'แทรปบาร์',
  'upper body ergometer': 'เครื่องปั่นแขน',
  weighted: 'ถ่วงน้ำหนัก',
  'wheel roller': 'ล้อบริหาร',
}

export const HEALTH_TARGET_LABELS: Record<string, string> = {
  abductors: 'กล้ามเนื้อกางสะโพก',
  abs: 'หน้าท้อง',
  adductors: 'กล้ามเนื้อหุบสะโพก',
  biceps: 'ไบเซปส์',
  brachialis: 'ต้นแขนด้านใน',
  calves: 'น่อง',
  'cardiovascular system': 'ระบบหัวใจและหลอดเลือด',
  delts: 'หัวไหล่',
  forearms: 'ท่อนแขน',
  glutes: 'สะโพก',
  hamstrings: 'ต้นขาหลัง',
  lats: 'ปีกหลัง',
  'levator scapulae': 'กล้ามเนื้อยกสะบัก',
  pectorals: 'อก',
  quads: 'ต้นขาหน้า',
  'serratus anterior': 'ชายโครงหน้า',
  spine: 'แนวกระดูกสันหลัง',
  traps: 'บ่า',
  triceps: 'ไตรเซปส์',
  'upper back': 'หลังส่วนบน',
}

export const HEALTH_EXERCISE_CATALOG: HealthCatalogExercise[] = GENERATED_HEALTH_EXERCISE_CATALOG
