import type { HealthAchievement, HealthQuest } from '@/types/health'

export const DEFAULT_HEALTH_QUESTS: HealthQuest[] = [
  {
    id: 'recovery-stretch-5',
    title: 'ยืดเหยียด 5 นาที',
    description: 'คลายตัวแบบช้า ๆ เหมาะกับวันที่อยากพักและขยับเบา ๆ',
    mode: 'recovery',
    durationMin: 5,
    xpReward: 25,
    exercises: [
      {
        id: 'neck-release',
        name: 'คลายคอ',
        emoji: '🌿',
        instruction: 'เอียงคอซ้ายขวาช้า ๆ ไม่ฝืนช่วงที่ตึง',
        targetText: '30 วินาที',
        durationSec: 30,
      },
      {
        id: 'shoulder-roll',
        name: 'หมุนไหล่',
        emoji: '🌀',
        instruction: 'หมุนไหล่ไปด้านหลังช้า ๆ แล้วสลับไปด้านหน้า',
        targetText: '8 รอบ',
        reps: 8,
      },
      {
        id: 'seated-forward-fold',
        name: 'ก้มตัวเบา ๆ',
        emoji: '🙆',
        instruction: 'ก้มตัวเท่าที่สบาย หายใจยาว ๆ และพักได้เสมอ',
        targetText: '45 วินาที',
        durationSec: 45,
      },
      {
        id: 'ankle-circle',
        name: 'หมุนข้อเท้า',
        emoji: '🦶',
        instruction: 'หมุนข้อเท้าช้า ๆ ทีละข้าง เพื่อปลุกการไหลเวียน',
        targetText: 'ข้างละ 6 รอบ',
        reps: 12,
      },
    ],
  },
  {
    id: 'easy-move-5',
    title: 'ขยับเบา ๆ 5 นาที',
    description: 'ขยับร่างกายแบบสบาย ๆ ให้วันนี้มีจังหวะเล็ก ๆ',
    mode: 'easy',
    durationMin: 5,
    xpReward: 30,
    exercises: [
      {
        id: 'march-in-place',
        name: 'เดินอยู่กับที่',
        emoji: '🚶',
        instruction: 'เดินอยู่กับที่ในจังหวะที่หายใจสะดวก',
        targetText: '60 วินาที',
        durationSec: 60,
      },
      {
        id: 'arm-swing',
        name: 'แกว่งแขน',
        emoji: '🙌',
        instruction: 'แกว่งแขนเบา ๆ ปล่อยไหล่ให้สบาย',
        targetText: '45 วินาที',
        durationSec: 45,
      },
      {
        id: 'side-step',
        name: 'ก้าวข้าง',
        emoji: '↔️',
        instruction: 'ก้าวซ้ายขวาช้า ๆ จับเก้าอี้ได้ถ้าต้องการ',
        targetText: '10 ครั้ง',
        reps: 10,
      },
      {
        id: 'easy-breath',
        name: 'หายใจปิดท้าย',
        emoji: '🍃',
        instruction: 'หายใจเข้าออกช้า ๆ ให้ร่างกายค่อย ๆ กลับมานิ่ง',
        targetText: '30 วินาที',
        durationSec: 30,
      },
    ],
  },
  {
    id: 'full-body-10',
    title: 'Full Body 10 นาที',
    description: 'ภารกิจทั้งตัวแบบพอดี ๆ เลือกพักเพิ่มได้ทุกช่วง',
    mode: 'normal',
    durationMin: 10,
    xpReward: 55,
    exercises: [
      {
        id: 'chair-squat',
        name: 'นั่งยืนจากเก้าอี้',
        emoji: '🪑',
        instruction: 'ลุกและนั่งช้า ๆ ใช้เก้าอี้ช่วยให้มั่นคง',
        targetText: '8 ครั้ง',
        reps: 8,
      },
      {
        id: 'wall-push',
        name: 'ดันกำแพง',
        emoji: '🧱',
        instruction: 'วางมือบนกำแพงแล้วดันกลับอย่างนุ่มนวล',
        targetText: '8 ครั้ง',
        reps: 8,
      },
      {
        id: 'standing-knee-lift',
        name: 'ยกเข่าสลับ',
        emoji: '🦵',
        instruction: 'ยกเข่าสลับข้าง จับพนักเก้าอี้ได้ถ้าต้องการ',
        targetText: '12 ครั้ง',
        reps: 12,
      },
      {
        id: 'back-reach',
        name: 'เอื้อมแขนเปิดอก',
        emoji: '✨',
        instruction: 'เอื้อมแขนออกด้านข้าง เปิดอกเท่าที่รู้สึกสบาย',
        targetText: '45 วินาที',
        durationSec: 45,
      },
      {
        id: 'cooldown-breath',
        name: 'หายใจคูลดาวน์',
        emoji: '🌙',
        instruction: 'หายใจยาว ๆ และสังเกตว่าร่างกายรู้สึกอย่างไร',
        targetText: '60 วินาที',
        durationSec: 60,
      },
    ],
  },
  {
    id: 'short-core-8',
    title: 'Core สั้น ๆ 8 นาที',
    description: 'เสริมแกนกลางแบบสั้น ๆ ไม่ต้องรีบและพักได้เมื่อจำเป็น',
    mode: 'normal',
    durationMin: 8,
    xpReward: 45,
    exercises: [
      {
        id: 'seated-knee-tuck',
        name: 'ดึงเข่านั่ง',
        emoji: '🪑',
        instruction: 'นั่งหลังตรง ดึงเข่าเข้าหาตัวทีละข้างแบบช้า ๆ',
        targetText: '10 ครั้ง',
        reps: 10,
      },
      {
        id: 'dead-bug-easy',
        name: 'Dead Bug เบา ๆ',
        emoji: '🐞',
        instruction: 'นอนหงาย ขยับแขนขาสลับกันเท่าที่ควบคุมได้',
        targetText: '8 ครั้ง',
        reps: 8,
      },
      {
        id: 'standing-side-bend',
        name: 'เอนตัวด้านข้าง',
        emoji: '🌾',
        instruction: 'ยืนมั่นคงแล้วเอนตัวซ้ายขวาแบบไม่ฝืน',
        targetText: 'ข้างละ 6 ครั้ง',
        reps: 12,
      },
      {
        id: 'core-breath',
        name: 'หายใจเก็บจังหวะ',
        emoji: '🍃',
        instruction: 'วางมือที่ท้อง หายใจให้ช้าและสบาย',
        targetText: '45 วินาที',
        durationSec: 45,
      },
    ],
  },
  {
    id: 'desk-break-5',
    title: 'Desk Break 5 นาที',
    description: 'พักจากหน้าจอแบบสั้น ๆ ให้คอ ไหล่ และหลังได้เปลี่ยนท่า',
    mode: 'recovery',
    durationMin: 5,
    xpReward: 25,
    exercises: [
      {
        id: 'screen-away-breath',
        name: 'มองไกลและหายใจ',
        emoji: '👀',
        instruction: 'มองออกไปไกล ๆ แล้วหายใจช้า ๆ',
        targetText: '40 วินาที',
        durationSec: 40,
      },
      {
        id: 'wrist-release',
        name: 'คลายข้อมือ',
        emoji: '🤲',
        instruction: 'หมุนข้อมือและสะบัดนิ้วเบา ๆ',
        targetText: '8 รอบ',
        reps: 8,
      },
      {
        id: 'desk-back-stretch',
        name: 'ยืดหลังกับโต๊ะ',
        emoji: '🧘',
        instruction: 'วางมือบนโต๊ะ ถอยตัวเล็กน้อย ยืดหลังเท่าที่สบาย',
        targetText: '45 วินาที',
        durationSec: 45,
      },
      {
        id: 'stand-and-reset',
        name: 'ลุกยืนรีเซ็ต',
        emoji: '🌤️',
        instruction: 'ลุกยืน ขยับเท้า และกลับมานั่งเมื่อพร้อม',
        targetText: '60 วินาที',
        durationSec: 60,
      },
    ],
  },
]

export const DEFAULT_HEALTH_ACHIEVEMENTS: HealthAchievement[] = [
  {
    id: 'first-quest',
    title: 'ภารกิจแรก',
    description: 'จบ Health Quest ครั้งแรก',
    emoji: '🌱',
    unlocked: false,
  },
  {
    id: 'three-sessions',
    title: 'ทำครบ 3 ครั้ง',
    description: 'สะสม session ที่มี XP ครบ 3 ครั้ง',
    emoji: '✨',
    unlocked: false,
  },
  {
    id: 'seven-sessions',
    title: 'ทำครบ 7 ครั้ง',
    description: 'สะสม session ที่มี XP ครบ 7 ครั้ง',
    emoji: '🏅',
    unlocked: false,
  },
  {
    id: 'three-day-streak',
    title: 'ทำต่อเนื่อง 3 วัน',
    description: 'ดูแลตัวเองต่อเนื่อง 3 วัน',
    emoji: '🔥',
    unlocked: false,
  },
  {
    id: 'try-recovery',
    title: 'ลองโหมดฟื้นฟู',
    description: 'จบ quest โหมด recovery อย่างนุ่มนวล',
    emoji: '🌿',
    unlocked: false,
  },
  {
    id: 'comeback',
    title: 'กลับมาเริ่มใหม่',
    description: 'กลับมาจบ quest หลังเว้นไปอย่างน้อย 2 วัน',
    emoji: '🌤️',
    unlocked: false,
  },
]
